#!/usr/bin/env bash
# Commit anything new under `reports/` back to the repo.
#
# Designed to run inside a GitHub Actions job after `validate-ci.sh` so
# the generated HTML is preserved alongside the code instead of being lost
# with the runner. Idempotent: exits silently if nothing changed.
#
# Target branch:
#   - tag push (refs/tags/*) → repo default branch
#   - everything else        → ${GITHUB_REF_NAME} (the branch that ran)
#
# Loop prevention: the ci.yml workflow uses `paths-ignore: ['reports/**']`
# so this push does NOT re-trigger CI. No `[skip ci]` needed (GitHub
# Actions doesn't honour that convention anyway).
set -euo pipefail

if [[ -z "${GITHUB_REF:-}" || -z "${GITHUB_REF_NAME:-}" ]]; then
  echo "GITHUB_REF / GITHUB_REF_NAME not set — refusing to run outside CI."
  exit 0
fi

# Default branch for tag pushes (release tags don't sit on a branch ref).
if [[ "$GITHUB_REF" == refs/tags/* ]]; then
  TARGET="${GITHUB_REPOSITORY_DEFAULT_BRANCH:-main}"
else
  TARGET="${GITHUB_REF_NAME}"
fi

echo "::group::commit-report → target branch: ${TARGET}"

git config user.name  "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

# Prefer a PAT (SUBMIT_TOKEN) over the default workflow token for the
# push: branch-protection rules on `main` reject the workflow token but
# allow a maintainer PAT to bypass (so the report lands directly on main
# without creating a chore(report) PR that itself has to clear required
# checks). Falls back to GITHUB_TOKEN when SUBMIT_TOKEN isn't set, which
# keeps the PR fallback below as a last-resort safety net.
PUSH_TOKEN="${SUBMIT_TOKEN:-${GITHUB_TOKEN:-}}"
if [[ -n "$PUSH_TOKEN" ]]; then
  REMOTE_URL_BASE="${GITHUB_SERVER_URL:-https://github.com}"
  REMOTE_URL_BASE="${REMOTE_URL_BASE#https://}"
  git remote set-url origin "https://x-access-token:${PUSH_TOKEN}@${REMOTE_URL_BASE}/${GITHUB_REPOSITORY}.git"
fi

# Switch to the target branch. Tag pushes leave us on a detached HEAD —
# checkout main explicitly. For branch pushes we're already there, but
# `git checkout "$TARGET"` is a safe no-op.
git fetch origin "$TARGET" --depth=1
git checkout "$TARGET"
# Make sure we're at the tip so the push isn't a non-fast-forward. If a
# parallel commit landed since the workflow started, rebase will surface
# that here and the push will retry naturally on the next run.
git pull --rebase origin "$TARGET" || true

git add reports/ 2>/dev/null || true
if git diff --staged --quiet; then
  echo "no report changes — nothing to commit"
  echo "::endgroup::"
  exit 0
fi

SHORT_SHA="$(git rev-parse --short HEAD)"
RUN_URL="${GITHUB_SERVER_URL:-https://github.com}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
COMMIT_MSG="chore(report): CI report from ${SHORT_SHA}

Generated by ${GITHUB_WORKFLOW} run ${GITHUB_RUN_NUMBER}.
See ${RUN_URL}"
git commit -m "$COMMIT_MSG"

# Direct push first. If the target branch is protected (rules require
# PR review / status checks / signed commits) the push will be rejected;
# fall back to a throw-away branch + auto-merging PR so the report still
# lands on ${TARGET} without needing the protection rules changed.
if git push origin "$TARGET" 2>&1; then
  echo "report committed to ${TARGET}"
  echo "::endgroup::"
  exit 0
fi

echo "direct push to ${TARGET} was rejected — falling back to PR"
BRANCH="auto/reports-${GITHUB_RUN_ID:-$(date +%s)}"
git checkout -b "$BRANCH"
git push origin "$BRANCH"

if command -v gh >/dev/null 2>&1; then
  PR_URL=$(gh pr create \
    --title "chore(report): CI report from ${SHORT_SHA}" \
    --body "$(printf 'Auto-generated by %s run %s.\n\nSee %s' "${GITHUB_WORKFLOW}" "${GITHUB_RUN_NUMBER}" "${RUN_URL}")" \
    --base "$TARGET" \
    --head "$BRANCH" 2>&1) || PR_URL=""
  echo "PR: ${PR_URL}"
  # Enable auto-merge (squash). If the repo doesn't allow auto-merge or
  # required checks haven't reported yet, this is a no-op — the PR stays
  # open for manual merge.
  gh pr merge "$BRANCH" --auto --squash --delete-branch 2>&1 || \
    echo "auto-merge unavailable — leave PR for manual merge"
else
  echo "gh CLI unavailable — branch ${BRANCH} pushed; open PR manually"
fi
echo "::endgroup::"
