#!/usr/bin/env bash
# Commit anything new under `reports/` back to the repo.
#
# Designed to run inside a GitHub Actions job after `validate-ci.sh` so
# the generated HTML is preserved alongside the code instead of being lost
# with the runner. Idempotent: exits silently if nothing changed.
#
# Target branch:
#   - tag push (refs/tags/*) → repo default branch
#   - everything else        → ${GITHUB_REF_NAME} (the branch that ran)
#
# Loop prevention: the ci.yml workflow uses `paths-ignore: ['reports/**']`
# so this push does NOT re-trigger CI. No `[skip ci]` needed (GitHub
# Actions doesn't honour that convention anyway).
set -euo pipefail

if [[ -z "${GITHUB_REF:-}" || -z "${GITHUB_REF_NAME:-}" ]]; then
  echo "GITHUB_REF / GITHUB_REF_NAME not set — refusing to run outside CI."
  exit 0
fi

# Default branch for tag pushes (release tags don't sit on a branch ref).
if [[ "$GITHUB_REF" == refs/tags/* ]]; then
  TARGET="${GITHUB_REPOSITORY_DEFAULT_BRANCH:-main}"
else
  TARGET="${GITHUB_REF_NAME}"
fi

echo "::group::commit-report → target branch: ${TARGET}"

git config user.name  "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

# Switch to the target branch. Tag pushes leave us on a detached HEAD —
# checkout main explicitly. For branch pushes we're already there, but
# `git checkout "$TARGET"` is a safe no-op.
git fetch origin "$TARGET" --depth=1
git checkout "$TARGET"
# Make sure we're at the tip so the push isn't a non-fast-forward. If a
# parallel commit landed since the workflow started, rebase will surface
# that here and the push will retry naturally on the next run.
git pull --rebase origin "$TARGET" || true

git add reports/ 2>/dev/null || true
if git diff --staged --quiet; then
  echo "no report changes — nothing to commit"
  echo "::endgroup::"
  exit 0
fi

SHORT_SHA="$(git rev-parse --short HEAD)"
RUN_URL="${GITHUB_SERVER_URL:-https://github.com}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
git commit -m "chore(report): CI report from ${SHORT_SHA}

Generated by ${GITHUB_WORKFLOW} run ${GITHUB_RUN_NUMBER}.
See ${RUN_URL}"

git push origin "$TARGET"
echo "report committed to ${TARGET}"
echo "::endgroup::"
