#!/usr/bin/env bash
# Commits new files under `reports/` back to the repo from a GitHub Actions job.
# Target: default branch for tag pushes, else ${GITHUB_REF_NAME}. Loop-safe via paths-ignore in ci.yml.
set -euo pipefail

if [[ -z "${GITHUB_REF:-}" || -z "${GITHUB_REF_NAME:-}" ]]; then
  echo "GITHUB_REF / GITHUB_REF_NAME not set — refusing to run outside CI."
  exit 0
fi

# Default branch for tag pushes (release tags don't sit on a branch ref).
if [[ "$GITHUB_REF" == refs/tags/* ]]; then
  TARGET="${GITHUB_REPOSITORY_DEFAULT_BRANCH:-main}"
else
  TARGET="${GITHUB_REF_NAME}"
fi

echo "::group::commit-report → target branch: ${TARGET}"

git config user.name  "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

# Prefer SUBMIT_TOKEN (PAT bypasses main's branch protection); fall back
# to GITHUB_TOKEN (PR fallback below is the last-resort safety net).
PUSH_TOKEN="${SUBMIT_TOKEN:-${GITHUB_TOKEN:-}}"
if [[ -n "$PUSH_TOKEN" ]]; then
  REMOTE_URL_BASE="${GITHUB_SERVER_URL:-https://github.com}"
  REMOTE_URL_BASE="${REMOTE_URL_BASE#https://}"
  git remote set-url origin "https://x-access-token:${PUSH_TOKEN}@${REMOTE_URL_BASE}/${GITHUB_REPOSITORY}.git"
fi

# Switch to target branch (tag push starts detached). Branch push is a no-op.
git fetch origin "$TARGET" --depth=1
git checkout "$TARGET"
# Ensure tip-of-branch — rebase any parallel landed commit; next run retries naturally.
git pull --rebase origin "$TARGET" || true

git add site/reports/ 2>/dev/null || true
if git diff --staged --quiet; then
  echo "no report changes — nothing to commit"
  echo "::endgroup::"
  exit 0
fi

SHORT_SHA="$(git rev-parse --short HEAD)"
RUN_URL="${GITHUB_SERVER_URL:-https://github.com}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
COMMIT_MSG="chore(report): CI report from ${SHORT_SHA}

Generated by ${GITHUB_WORKFLOW} run ${GITHUB_RUN_NUMBER}.
See ${RUN_URL}"
git commit -m "$COMMIT_MSG"

# Try direct push; if branch protection rejects it, fall back to
# throw-away branch + auto-merging PR so the report still lands on ${TARGET}.
if git push origin "$TARGET" 2>&1; then
  echo "report committed to ${TARGET}"
  echo "::endgroup::"
  exit 0
fi

echo "direct push to ${TARGET} was rejected — falling back to PR"
BRANCH="auto/reports-${GITHUB_RUN_ID:-$(date +%s)}"
git checkout -b "$BRANCH"
git push origin "$BRANCH"

if command -v gh >/dev/null 2>&1; then
  PR_URL=$(gh pr create \
    --title "chore(report): CI report from ${SHORT_SHA}" \
    --body "$(printf 'Auto-generated by %s run %s.\n\nSee %s' "${GITHUB_WORKFLOW}" "${GITHUB_RUN_NUMBER}" "${RUN_URL}")" \
    --base "$TARGET" \
    --head "$BRANCH" 2>&1) || PR_URL=""
  echo "PR: ${PR_URL}"
  # Enable auto-merge (squash). If the repo doesn't allow auto-merge or
  # required checks haven't reported yet, this is a no-op — the PR stays
  # open for manual merge.
  gh pr merge "$BRANCH" --auto --squash --delete-branch 2>&1 || \
    echo "auto-merge unavailable — leave PR for manual merge"
else
  echo "gh CLI unavailable — branch ${BRANCH} pushed; open PR manually"
fi
echo "::endgroup::"
